version: "3"
services:
  app_hub:
    image: alpine
    tty: true
    networks: 
      - canbus0
      - canbus1
  app_can0:
    image: alpine 
    tty: true
    networks: [ canbus0 ]
  app_can1:
    image: alpine 
    tty: true
    networks: [ canbus1 ]
networks:
  canbus0:
    driver: wsovalle/vxcan:latest
    driver_opts:
      vxcan.dev: can_host
      vxcan.peer: can_docker
      vxcan.id: 0
  canbus1:
    driver: wsovalle/vxcan:latest
    driver_opts:
      vxcan.dev: can_host
      vxcan.peer: can_docker
      vxcan.id: 1  
